---
#- hosts: "{{ inventory_hostname }}"
- name:  Write test to a remote file
  become: yes
  hosts: all
  tasks:
  - name: Create test
    copy:
      content:  "ANSIBLE TEST ANSIBLE TEST"
      dest: /tmp/ansibletest.txt
