---
#- hosts: "{{ inventory_hostname }}"
- name:  Write test to a remote file
  become: yes
  hosts: all
  tasks:
  - name: Create test
    copy:
      content:  "TEST TEST"
      dest: /tmp/steve.txt
