---
# vars file for roles/dnf-update
dnf_name: "*"
dnf_state: latest
dnf_enablerepo: "rhel-8-for-x86_64-appstream-rpms,rhel-8-for-x86_64-baseos-rpms,satellite-tools-6.?-for-rhel-8-x86_64-rpms"
dnf_disablerepo: "*"
dnf_exclude: ""

